# Generated by Django 5.2.5 on 2026-06-03 23:29

import django.db.models.deletion
import utils.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='公司编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('industry', models.CharField(max_length=255, null=True, verbose_name='所属行业')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='公司描述')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='公司有效期')),
                ('tier_level', models.IntegerField(default=1, verbose_name='公司层级')),
                ('tenant_slug', models.CharField(default=utils.tenant.generate_tenant_slug, help_text='租户唯一标识，用于文件存储隔离和外部引用', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='用户ID')),
                ('user_name', models.CharField(db_index=True, max_length=50, verbose_name='用户名称')),
                ('user_role', models.CharField(max_length=255, null=True, verbose_name='用户角色')),
                ('com_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='公司ID')),
                ('com_name', models.CharField(db_index=True, max_length=50, null=True, verbose_name='公司名称')),
                ('org_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='组织ID')),
                ('org_name', models.CharField(max_length=50, null=True, verbose_name='组织名称')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('export', '导出'), ('import', '导入'), ('login', '登录'), ('logout', '登出'), ('reset_password', '重置密码'), ('change_password', '修改密码')], max_length=20, null=True, verbose_name='操作类型')),
                ('target_type', models.CharField(max_length=50, null=True, verbose_name='操作对象类型')),
                ('target_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='操作对象ID')),
                ('target_name', models.CharField(max_length=50, null=True, verbose_name='操作对象名称')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='操作详情')),
                ('status', models.CharField(choices=[('success', '成功'), ('failure', '失败')], default='success', max_length=20, null=True, verbose_name='操作结果')),
                ('error_summary', models.CharField(max_length=255, null=True, verbose_name='错误摘要')),
                ('ip_address', models.CharField(max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(max_length=255, null=True, verbose_name='用户代理')),
                ('client_type', models.CharField(max_length=50, null=True, verbose_name='客户端类型')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限代码')),
                ('parent_code', models.CharField(max_length=50, null=True, verbose_name='父级权限代码')),
                ('type', models.CharField(default='menu', max_length=20, verbose_name='权限类型')),
                ('module', models.CharField(max_length=50, null=True, verbose_name='关联模块')),
                ('sort_order', models.IntegerField(default=0, null=True, verbose_name='排序')),
                ('tier_level', models.PositiveSmallIntegerField(default=1, verbose_name='权限等级（不同应用等级）')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='权限描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255, verbose_name='组织名称')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='组织编码')),
                ('org_type', models.CharField(choices=[('group', '集团'), ('subsidiary', '子公司'), ('division', '事业部'), ('department', '部门'), ('workshop', '车间'), ('section', '工段'), ('team', '班组')], max_length=50, null=True, verbose_name='组织类型')),
                ('description', models.TextField(null=True, verbose_name='组织描述')),
                ('level', models.IntegerField(null=True, verbose_name='组织层级')),
                ('path', models.CharField(max_length=255, null=True, verbose_name='组织路径')),
                ('sort_order', models.IntegerField(default=0, null=True, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_orgs', to='identity.company', verbose_name='所属公司')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='identity.organization')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='AccessibleOrganization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.organization')),
            ],
            options={
                'verbose_name': '可访问组织',
                'verbose_name_plural': '可访问组织',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='角色编码，用于程序识别')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='identity.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('engineer_name', models.CharField(max_length=50, null=True, verbose_name='工程师姓名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=True, verbose_name='是否员工')),
                ('is_tenant_admin', models.BooleanField(default=False, verbose_name='是否租户管理员')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级管理员')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_login_at', models.DateTimeField(null=True, verbose_name='上次登录时间')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='用户有效期')),
                ('feishu_id', models.CharField(max_length=50, null=True, verbose_name='飞书用户ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.company', verbose_name='所属公司')),
                ('extra_accessible_orgs', models.ManyToManyField(related_name='extra_authorized_users', through='identity.AccessibleOrganization', through_fields=('user', 'organization'), to='identity.organization', verbose_name='额外授权的可访问组织信息')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='identity.organization', verbose_name='所属组织')),
                ('roles', models.ManyToManyField(related_name='belong_users', to='identity.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(db_index=True, max_length=255, verbose_name='哈希Token')),
                ('ua', models.CharField(default='', max_length=512, verbose_name='用户代理')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否撤销')),
                ('ip_address', models.CharField(default='', max_length=45, verbose_name='IP地址')),
                ('expires_at', models.DateTimeField(null=True, verbose_name='过期时间')),
                ('revoked_at', models.DateTimeField(null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='identity.user', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedirectToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='跳转令牌')),
                ('target_url', models.TextField(verbose_name='目标地址')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '追踪模型',
                'verbose_name_plural': '追踪模型',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orgs', to='identity.user', verbose_name='组织负责人'),
        ),
        migrations.AddField(
            model_name='accessibleorganization',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_made', to='identity.user'),
        ),
        migrations.AddField(
            model_name='accessibleorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.user'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(db_index=True, max_length=100, verbose_name='权限代码')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='identity.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限关系',
                'verbose_name_plural': '角色权限关系',
                'unique_together': {('role', 'permission_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='accessibleorganization',
            unique_together={('user', 'organization')},
        ),
    ]
