# Generated by Django 4.2.30 on 2026-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='业务代号（默认基于名称自动生成，可手动调整）', max_length=30, null=True, unique=True, verbose_name='公司代号'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, help_text='业务代号（默认基于名称自动生成，可手动调整）', max_length=30, null=True, verbose_name='组织代号'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'code')},
        ),
    ]
