[uwsgi]
socket=0.0.0.0:9212
buffer-size=102400
home=/home/molding/.pyenv/versions/molding
chdir=/opt/inovance/app
module=base.wsgi
processes=2
threads=2
master=true
socket-timeout=5
listen=1024
need-app=true
die-on-term=false
max-requests=1000
lazy-app=true
