# Generated by Django 5.2.5 on 2026-06-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessIndex',
        ),
    ]
