# Generated by Django 5.2.5 on 2026-06-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_delete_processindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processparameter',
            name='BT1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT5',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT6',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT7',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT8',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='BT9',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='CT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DDAM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DDBM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DMAM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DMBM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DPAM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DPBM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DTAM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DTBM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DVAM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='DVBM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IDT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IL5',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IP5',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='IV5',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MBP0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MBP1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MBP2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MBP3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MDT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MEL',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='ML0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='ML1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='ML2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='ML3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MP0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MP1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MP2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MP3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MSR0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MSR1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MSR2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='MSR3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='NT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PP0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PP1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PP2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PP3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PP4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PT0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PT1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PT2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PT3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PT4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PV0',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PV1',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PV2',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PV3',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='PV4',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='VPTL',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='VPTM',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='VPTP',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='VPTT',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='VPTV',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='barrel_temperature_stages',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='holding_stages',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='injection_stages',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='metering_stages',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='parameter_code',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='parameter_source',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='parent_parameter',
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='sequence_index',
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_6',
            field=models.FloatField(blank=True, null=True, verbose_name='六段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_7',
            field=models.FloatField(blank=True, null=True, verbose_name='七段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_8',
            field=models.FloatField(blank=True, null=True, verbose_name='八段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_9',
            field=models.FloatField(blank=True, null=True, verbose_name='九段料筒温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='brl_temp_stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='料筒温度段数 1-10'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='cool_t',
            field=models.FloatField(blank=True, null=True, verbose_name='冷却时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_pres_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段保压压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_pres_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段保压压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_pres_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段保压压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_pres_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段保压压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_pres_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段保压压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_spd_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段保压速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_spd_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段保压速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_spd_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段保压速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_spd_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段保压速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_spd_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段保压速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='保压段数 1-5'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_t_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段保压时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_t_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段保压时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_t_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段保压时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_t_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段保压时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='hold_t_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段保压时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_dly_t',
            field=models.FloatField(blank=True, null=True, verbose_name='注射延时'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pos_6',
            field=models.FloatField(blank=True, null=True, verbose_name='六段注射位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_pres_6',
            field=models.FloatField(blank=True, null=True, verbose_name='六段注射压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_5',
            field=models.FloatField(blank=True, null=True, verbose_name='五段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_spd_6',
            field=models.FloatField(blank=True, null=True, verbose_name='六段注射速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='注射段数 1-6'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='inj_t',
            field=models.FloatField(blank=True, null=True, verbose_name='注射时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_back_pres_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段背压'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_back_pres_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段背压'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_back_pres_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段背压'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_back_pres_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段背压'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_end_pos',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶终止位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_lim_t',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶延时'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pos_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段熔胶位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pos_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段熔胶位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pos_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段熔胶位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pos_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段熔胶位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pres_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段熔胶压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pres_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段熔胶压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pres_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段熔胶压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_pres_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段熔胶压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_rot_spd_1',
            field=models.FloatField(blank=True, null=True, verbose_name='一段螺杆转速'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_rot_spd_2',
            field=models.FloatField(blank=True, null=True, verbose_name='二段螺杆转速'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_rot_spd_3',
            field=models.FloatField(blank=True, null=True, verbose_name='三段螺杆转速'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_rot_spd_4',
            field=models.FloatField(blank=True, null=True, verbose_name='四段螺杆转速'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='met_stg',
            field=models.IntegerField(blank=True, null=True, verbose_name='熔胶段数 1-4'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='noz_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='喷嘴温度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='param_code',
            field=models.CharField(blank=True, help_text='工艺参数编号', max_length=50, null=True, verbose_name='工艺参数编号'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='param_source',
            field=models.CharField(blank=True, choices=[('unknown', '未知'), ('manual', '手工录入'), ('import', '外部导入'), ('algorithm_init', '算法初始化'), ('system_inferred', '系统推理'), ('manual_adjusted', '人工调整'), ('equipment_sync', '设备同步'), ('template_copy', '模板复制')], default='unknown', max_length=20, null=True, verbose_name='参数来源'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='parent_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='process.processparameter'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pre_met_decomp_dist',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶前松退距离'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pre_met_decomp_mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='熔胶前松退模式'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pre_met_decomp_pres',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶前松退压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pre_met_decomp_spd',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶前松退速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pre_met_decomp_t',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶前松退时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pst_met_decomp_dist',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶后松退距离'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pst_met_decomp_mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='熔胶后松退模式'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pst_met_decomp_pres',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶后松退压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pst_met_decomp_spd',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶后松退速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='pst_met_decomp_t',
            field=models.FloatField(blank=True, null=True, verbose_name='熔胶后松退时间'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='seq_idx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='序列序号'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='vps_mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='VP切换模式'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='vps_pos',
            field=models.FloatField(blank=True, null=True, verbose_name='VP切换位置'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='vps_pres',
            field=models.FloatField(blank=True, null=True, verbose_name='VP切换压力'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='vps_spd',
            field=models.FloatField(blank=True, null=True, verbose_name='VP切换速度'),
        ),
        migrations.AddField(
            model_name='processparameter',
            name='vps_t',
            field=models.FloatField(blank=True, null=True, verbose_name='VP切换时间'),
        ),
    ]
