# Generated by Django 5.2.5 on 2026-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_add_fuzzy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcondition',
            name='process_context',
            field=models.JSONField(blank=True, help_text='\n        前端传给后端的业务覆盖与调整值。与 process_context_snapshot\n        并存：snapshot 是后端不可变快照（创建时锁定），context 是\n        前端可变的覆盖输入（用于指导后端处理）。\n        {\n            "product_weight": 85,\n            "runner_weight": 0,\n            "gate_type": "侧浇口",\n            "ave_thickness": 2.8,\n            "max_thickness": 3.5,\n            "max_length": 150,\n            "gate_radius": 1.5,\n            "gate_length": 2.0,\n            "gate_width": 3.0\n        }\n        ', null=True, verbose_name='工艺上下文（前端输入）'),
        ),
    ]
