# Generated by Django 5.2.5 on 2026-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_processcondition_process_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcondition',
            name='condition_code',
        ),
        migrations.AddField(
            model_name='processcondition',
            name='condition_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工艺条件编号'),
        ),
    ]
