# Generated by Django 5.2.5 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_company_code_alter_organization_code_and_more'),
        ('process', '0004_remove_processcondition_condition_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantkeywordoverride',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tenantkeywordoverride',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='tenantkeywordoverride',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='rulemethod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='expertrule',
            unique_together={('rule_library', 'rule_code')},
        ),
        migrations.RemoveField(
            model_name='processparameter',
            name='param_code',
        ),
        migrations.AlterUniqueTogether(
            name='rulekeyword',
            unique_together={('company', 'keyword_name')},
        ),
        migrations.RemoveField(
            model_name='rulelibrary',
            name='parent_library',
        ),
        migrations.AddField(
            model_name='processparameter',
            name='parameter_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工艺参数编号'),
        ),
        migrations.AddField(
            model_name='rulekeyword',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='参数说明'),
        ),
        migrations.AddField(
            model_name='rulelibrary',
            name='library_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='规则库编号'),
        ),
        migrations.AddField(
            model_name='rulemethod',
            name='defect_code',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='缺陷标识'),
        ),
        migrations.AddField(
            model_name='rulemethod',
            name='defect_label',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='缺陷名称'),
        ),
        migrations.AddField(
            model_name='rulemethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='rulemethod',
            name='polymer_abbreviation',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='材料缩写'),
        ),
        migrations.AddField(
            model_name='rulemethod',
            name='rule_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='规则编号'),
        ),
        migrations.AlterField(
            model_name='expertrule',
            name='rule_code',
            field=models.CharField(max_length=50, verbose_name='规则编码'),
        ),
        migrations.AlterField(
            model_name='processcondition',
            name='status',
            field=models.CharField(blank=True, choices=[('active', '使用中'), ('archived', '已归档')], max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='rulekeyword',
            name='fuzzy_level',
            field=models.IntegerField(choices=[(3, '3级'), (5, '5级'), (7, '7级'), (9, '9级')], default=5, verbose_name='模糊级别'),
        ),
        migrations.AlterField(
            model_name='rulekeyword',
            name='keyword_name',
            field=models.CharField(max_length=50, verbose_name='关键词名称'),
        ),
        migrations.AlterField(
            model_name='rulekeyword',
            name='keyword_type',
            field=models.CharField(choices=[('pressure', '压力'), ('speed', '速度'), ('time', '时间'), ('temperature', '温度'), ('position', '位置'), ('force', '力'), ('length', '长度'), ('weight', '重量')], max_length=20, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='rulelibrary',
            name='library_code',
            field=models.CharField(max_length=50, verbose_name='规则库编码'),
        ),
        migrations.AlterField(
            model_name='rulelibrary',
            name='owner_type',
            field=models.CharField(choices=[('system', '系统级'), ('tenant', '租户级')], max_length=20, verbose_name='归属类型'),
        ),
        migrations.AlterField(
            model_name='rulemethod',
            name='confidence',
            field=models.FloatField(default=1.0, verbose_name='置信度（0~1）'),
        ),
        migrations.AlterField(
            model_name='rulemethod',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='优先级（0~10）'),
        ),
        migrations.DeleteModel(
            name='MinedRule',
        ),
        migrations.DeleteModel(
            name='TenantKeywordOverride',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='defect_desc',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='defect_name',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='is_auto',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='polymer_category',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='rule_code',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='rule_content',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='rule_level',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='rulemethod',
            name='subrule_no',
        ),
        migrations.RemoveField(
            model_name='expertrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expertrule',
            name='parent_rule',
        ),
        migrations.RemoveField(
            model_name='expertrule',
            name='source',
        ),
        migrations.RemoveField(
            model_name='expertrule',
            name='version',
        ),
        migrations.RemoveField(
            model_name='rulekeyword',
            name='param_group',
        ),
        migrations.RemoveField(
            model_name='rulekeyword',
            name='polymer_abbreviation',
        ),
        migrations.RemoveField(
            model_name='rulekeyword',
            name='product_small_type',
        ),
        migrations.RemoveField(
            model_name='rulekeyword',
            name='subrule_no',
        ),
    ]
