# Generated by Django 5.2.5 on 2026-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_company_code_alter_organization_code_and_more'),
        ('process', '0005_remove_tenantkeywordoverride_company_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rulemethod',
            index=models.Index(fields=['defect_label', 'is_active', 'is_deleted'], name='process_rul_defect__d8d266_idx'),
        ),
        migrations.AddIndex(
            model_name='rulemethod',
            index=models.Index(fields=['rule_library', 'priority'], name='process_rul_rule_li_0a82f0_idx'),
        ),
        migrations.AddIndex(
            model_name='rulemethod',
            index=models.Index(fields=['is_active', 'is_deleted'], name='process_rul_is_acti_d089dc_idx'),
        ),
    ]
