# Generated by Django 4.2.30 on 2026-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_rulemethod_process_rul_defect__d8d266_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulekeyword',
            name='category',
            field=models.CharField(choices=[('parameter', '参数'), ('defect', '缺陷'), ('defect_position', '缺陷位置')], default='parameter', help_text='决定该关键词在 if-then 规则中能扮演的角色：参数（IF/THEN） / 缺陷（IF） / 缺陷位置（IF）', max_length=30, verbose_name='业务分类'),
        ),
        migrations.AddField(
            model_name='rulekeyword',
            name='parameter_kind',
            field=models.CharField(choices=[('setpoint', '设定值'), ('actual', '实际值')], default='setpoint', help_text='设定值：面板输入目标；实际值：设备通讯采集或手填实测', max_length=20, verbose_name='值类型'),
        ),
    ]
