# Generated by hand for library_type field
# - RuleLibrary.library_type: 'expert' (专家规则库) | 'fuzzy' (模糊规则库)
# - 默认 'expert'：保持现有数据语义（已有的 expert_rules 库都是专家规则库）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_rulekeyword_category_rulekeyword_parameter_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulelibrary',
            name='library_type',
            field=models.CharField(
                choices=[('expert', '专家规则库'), ('fuzzy', '模糊规则库')],
                default='expert',
                help_text='专家规则库：仅允许 ExpertRule；模糊规则库：仅允许 RuleMethod',
                max_length=20,
                verbose_name='库类型',
            ),
        ),
    ]