# Generated by hand for parameter_kind choices extension
# - RuleKeyword.parameter_kind: 增加 ('enum', '其它') 选项
# - 之前 0007 已添加字段（default='setpoint'，2 项 choices）
# - 现在扩展为 3 项 choices，已有数据的值不变（数据库值仍是 'setpoint' / 'actual'）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_rulelibrary_library_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulekeyword',
            name='parameter_kind',
            field=models.CharField(
                choices=[
                    ('setpoint', '设定值'),
                    ('actual', '实际值'),
                    ('enum', '其它'),
                ],
                default='setpoint',
                help_text='设定值：面板输入目标；实际值：设备通讯采集或手填实测；其它：不需要区分属性（缺陷/缺陷位置等）',
                max_length=20,
                verbose_name='属性值',
            ),
        ),
    ]