# Generated by Django 4.2.30 on 2026-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_rulekeyword_parameter_kind_enum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='adopted_param',
        ),
        migrations.RemoveField(
            model_name='tuningrecord',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tuningrecord',
            name='parameter_snapshot',
        ),
        migrations.AddField(
            model_name='tuningrecord',
            name='adjustments',
            field=models.JSONField(blank=True, default=dict, help_text='规范化调参内容，由系统自动生成（OLD vs NEW diff）', null=True, verbose_name='调整记录'),
        ),
        migrations.AddField(
            model_name='tuningrecord',
            name='previous_parameter',
            field=models.JSONField(blank=True, help_text='调整前的工艺参数快照（OLD parameter.parameters）', null=True, verbose_name='调整前参数快照'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_adopted',
            field=models.BooleanField(default=True, help_text='默认 True，下一轮 ineffective 时自动改为 False（训练标签）', verbose_name='是否被采纳'),
        ),
    ]
