# Generated by Django 5.2.5 on 2026-06-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavity',
            name='product_code',
            field=models.CharField(max_length=150, null=True, verbose_name='制品编号'),
        ),
        migrations.AlterField(
            model_name='cavity',
            name='product_name',
            field=models.CharField(max_length=150, null=True, verbose_name='制品名称'),
        ),
        migrations.AlterField(
            model_name='ejectionsystem',
            name='ejection_type',
            field=models.CharField(max_length=100, null=True, verbose_name='顶出类型'),
        ),
        migrations.AlterField(
            model_name='ejectionsystem',
            name='reset_method',
            field=models.CharField(max_length=100, null=True, verbose_name='复位方式'),
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(max_length=100, null=True, verbose_name='浇口类型'),
        ),
        migrations.AlterField(
            model_name='gatingsystem',
            name='hot_runner_system_type',
            field=models.CharField(max_length=100, null=True, verbose_name='热流道类型'),
        ),
        migrations.AlterField(
            model_name='gatingsystem',
            name='valve_actuation_type',
            field=models.CharField(max_length=150, null=True, verbose_name='针阀驱动方式'),
        ),
    ]
