# Generated by Django 5.2.5 on 2026-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatingsystem',
            name='runner_type',
            field=models.CharField(max_length=50, null=True, verbose_name='流道类型（热流道/冷流道/热转冷）'),
        ),
    ]
