# Generated by Django 4.2.30 on 2026-09-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_gatingsystem_runner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymermechanical',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_set', to='masterdata.polymer'),
        ),
        migrations.AlterField(
            model_name='polymerpvt',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvt_set', to='masterdata.polymer'),
        ),
        migrations.AlterField(
            model_name='polymerrheology',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rheology_set', to='masterdata.polymer'),
        ),
        migrations.AlterField(
            model_name='polymershrinkage',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrinkage_set', to='masterdata.polymer'),
        ),
    ]
