# Generated by hand for clamping_type / ejection_mode choices extension
# - InjectionMoldingMachine.clamping_type: 增加 ('hydraulic_toggle', '肘杆式液压锁模') 选项
#   + 同步 ('hydraulic', '液压锁模') label 改为 '液压锁模（直压式）'
# - InjectionMoldingMachine.ejection_mode: 增加 ('double_side_symmetric', '双侧对称顶出') 选项
# - 0001_initial 中已有 spring/hydraulic/servo 与 single_center/four_corner_symmetric/none

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_polymer_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionmoldingmachine',
            name='clamping_type',
            field=models.CharField(
                choices=[
                    ('spring', '弹簧锁模'),
                    ('hydraulic', '液压锁模（直压式）'),
                    ('hydraulic_toggle', '肘杆式液压锁模'),
                    ('servo', '伺服锁模'),
                ],
                help_text='锁模机构类型',
                max_length=50,
                null=True,
                verbose_name='锁模类型',
            ),
        ),
        migrations.AlterField(
            model_name='injectionmoldingmachine',
            name='ejection_mode',
            field=models.CharField(
                choices=[
                    ('single_center', '单中心顶出'),
                    ('double_side_symmetric', '双侧对称顶出'),
                    ('four_corner_symmetric', '四角对称顶出'),
                    ('none', '无自动顶出'),
                ],
                help_text='机器顶出机构的工作方式，用于匹配模具顶棍孔分布',
                max_length=50,
                null=True,
                verbose_name='顶出模式',
            ),
        ),
    ]