# Generated by Django 5.2.5 on 2026-06-03 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='文件UUID')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档'), ('other', '其他')], max_length=20, verbose_name='文件类别')),
                ('size', models.BigIntegerField(null=True, verbose_name='文件大小（字节）')),
                ('md5', models.CharField(db_index=True, max_length=32, verbose_name='文件MD5')),
                ('storage_path', models.CharField(max_length=512, verbose_name='存储路径')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.company', verbose_name='所属公司')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.organization', verbose_name='所属部门')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='identity.user', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.IntegerField(verbose_name='业务ID')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('usage_type', models.CharField(max_length=50, verbose_name='使用类型')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='filecenter.file')),
            ],
            options={
                'verbose_name': '文件引用',
                'verbose_name_plural': '文件引用',
                'indexes': [models.Index(fields=['business_type', 'business_id', 'usage_type'], name='file_ref_bus_usage_idx')],
            },
        ),
    ]
