# Generated by Django 5.2.5 on 2026-06-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filecenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filereference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
