
def make_perm(
    name: str,
    code: str,
    parent_code: str = "",
    type: str = "button",
    sort_order: int = 0,
    module: str = "",
    tier_level: int = 1,
    description: str = "",
    is_active: bool = True,
) -> dict:
    """构建权限项，提供清晰接口和合理默认值"""
    return {
        "name": name,
        "code": code,
        "parent_code": parent_code or "",
        "type": type,
        "sort_order": sort_order,
        "module": module,
        "tier_level": tier_level,
        "description": description,
        "is_active": is_active,
    }


PERMISSIONS = [
    # ─────────────── 系统根节点 ───────────────
    make_perm("系统权限", "system_permission", type="menu", sort_order=1),

    # ─────────────── 模具管理 ───────────────
    make_perm("模具管理", "mold_manage", parent_code="system_permission", type="menu", sort_order=1, module="mold"),
    make_perm("模具列表", "mold_list", parent_code="mold_manage", type="menu", sort_order=1, module="mold"),
    make_perm("查看模具", "review_mold", parent_code="mold_list", sort_order=1, module="mold"),
    make_perm("增加模具", "add_mold", parent_code="mold_list", sort_order=2, module="mold"),
    make_perm("删除模具", "delete_mold", parent_code="mold_list", sort_order=3, module="mold"),
    make_perm("修改模具", "update_mold", parent_code="mold_list", sort_order=4, module="mold"),
    make_perm("查看模流数据", "review_moldflow", parent_code="mold_list", sort_order=5, module="mold"),
    make_perm("查看试模履历", "review_trial_resume", parent_code="mold_list", sort_order=6, module="mold"),
    make_perm("查看问题点履历", "review_problem_resume", parent_code="mold_list", sort_order=7, module="mold"),
    make_perm("项目列表", "project_list", parent_code="mold_manage", type="menu", sort_order=2, module="mold"),
    make_perm("查看项目", "review_project", parent_code="project_list", sort_order=1, module="mold"),
    make_perm("增加项目", "add_project", parent_code="project_list", sort_order=2, module="mold"),
    make_perm("删除项目", "delete_project", parent_code="project_list", sort_order=3, module="mold"),
    make_perm("修改项目", "update_project", parent_code="project_list", sort_order=4, module="mold"),
    
    # ─────────────── 约机管理 ───────────────
    make_perm("约机管理", "reservation_manage", parent_code="system_permission", type="menu", sort_order=2, module="reservation"),
    make_perm("约机看板", "reservation_board", parent_code="reservation_manage", type="menu", sort_order=1, module="reservation"),
    make_perm("每日计划", "reservation_daily", parent_code="reservation_manage", type="menu", sort_order=2, module="reservation"),
    make_perm("约机列表", "reservation_list", parent_code="reservation_manage", type="menu", sort_order=3, module="reservation"),
    make_perm("查看约机", "review_reservation", parent_code="reservation_list", sort_order=1, module="reservation"),
    make_perm("增加约机", "add_reservation", parent_code="reservation_list", sort_order=2, module="reservation"),
    make_perm("删除约机", "delete_reservation", parent_code="reservation_list", sort_order=3, module="reservation"),
    make_perm("修改约机", "update_reservation", parent_code="reservation_list", sort_order=4, module="reservation"),
    make_perm("排程信息", "schedule_list", parent_code="reservation_manage", type="menu", sort_order=4, module="reservation"),
    make_perm("查看排程", "review_schedule", parent_code="schedule_list", sort_order=1, module="reservation"),
    make_perm("删除排程", "delete_schedule", parent_code="schedule_list", sort_order=2, module="reservation"),
    make_perm("修改排程", "update_schedule", parent_code="schedule_list", sort_order=3, module="reservation"),
    make_perm("计划制定", "reservation_plan", parent_code="reservation_manage", type="menu", sort_order=5, module="reservation"),
    make_perm("加入试模计划", "confirm_plan", parent_code="reservation_plan", sort_order=1, module="reservation"),
    make_perm("取消试模计划", "cancel_plan", parent_code="reservation_plan", sort_order=2, module="reservation"),
    make_perm("人员分配", "submit_assignment", parent_code="reservation_plan", sort_order=3, module="reservation"),
    make_perm("查看试模计划", "review_reservation_plan", parent_code="reservation_plan", sort_order=4, module="reservation"),
    make_perm("计划列表", "plan_list", parent_code="reservation_manage", type="menu", sort_order=6, module="reservation"),
    make_perm("查看计划时间节点", "review_plan", parent_code="plan_list", sort_order=1, module="reservation"),
    make_perm("修改计划时间节点", "update_plan", parent_code="plan_list", sort_order=2, module="reservation"),
    make_perm("试模完备", "readiness_list", parent_code="reservation_manage", type="menu", sort_order=7, module="reservation"),
    make_perm("查看完备总览", "readiness_overview", parent_code="readiness_list", sort_order=1, module="reservation"),
    make_perm("确认试模完备", "confirm_readiness", parent_code="readiness_list", sort_order=2, module="reservation"),
    make_perm("删除试模完备", "cancel_readiness", parent_code="readiness_list", sort_order=3, module="reservation"),
    make_perm("模具完备", "readiness_mold", parent_code="readiness_list", type="menu", sort_order=4, module="reservation"),
    make_perm("模具自检", "mold_inspection", parent_code="readiness_mold", sort_order=1, module="reservation"),
    make_perm("申请试模", "trial_request", parent_code="readiness_mold", sort_order=2, module="reservation"),
    make_perm("试模审批", "trial_approval", parent_code="readiness_mold", sort_order=3, module="reservation"),
    make_perm("装配班长审批", "trial_approval_bz", parent_code="trial_approval", sort_order=1, module="reservation"),
    make_perm("装配线长审批", "trial_approval_xz", parent_code="trial_approval", sort_order=2, module="reservation"),
    make_perm("质量检验审批", "trial_approval_zj", parent_code="trial_approval", sort_order=3, module="reservation"),
    make_perm("项目室审批", "trial_approval_xm", parent_code="trial_approval", sort_order=4, module="reservation"),
    make_perm("事业部审批", "trial_approval_syb", parent_code="trial_approval", sort_order=5, module="reservation"),
    make_perm("品质保证部审批", "trial_approval_pbb", parent_code="trial_approval", sort_order=6, module="reservation"),
    make_perm("模具移交", "mold_handover", parent_code="readiness_mold", sort_order=4, module="reservation"),
    make_perm("确认模具完备", "confirm_readiness_mold", parent_code="readiness_mold", sort_order=5, module="reservation"),
    make_perm("物料完备", "readiness_material", parent_code="readiness_list", type="menu", sort_order=5, module="reservation"),
    make_perm("注塑机完备", "readiness_injection", parent_code="readiness_list", type="menu", sort_order=6, module="reservation"),
    make_perm("辅机完备", "readiness_auxiliary", parent_code="readiness_list", type="menu", sort_order=7, module="reservation"),

    # ─────────────── 领料管理 ───────────────
    make_perm("领料管理", "inventory_manage", parent_code="system_permission", type="menu", sort_order=3, module="inventory"),
    make_perm("物料信息", "material_list", parent_code="inventory_manage", type="menu", sort_order=1, module="inventory"),
    make_perm("查看物料", "review_material", parent_code="material_list", sort_order=1, module="inventory"),
    make_perm("添加物料", "add_material", parent_code="material_list", sort_order=2, module="inventory"),
    make_perm("删除物料", "delete_material", parent_code="material_list", sort_order=3, module="inventory"),
    make_perm("修改物料", "update_material", parent_code="material_list", sort_order=4, module="inventory"),
    make_perm("库存列表", "inventory_list", parent_code="inventory_manage", type="menu", sort_order=2, module="inventory"),
    make_perm("查看库存", "review_inventory", parent_code="inventory_list", sort_order=1, module="inventory"),
    make_perm("添加库存", "add_inventory", parent_code="inventory_list", sort_order=2, module="inventory"),
    make_perm("删除库存", "delete_inventory", parent_code="inventory_list", sort_order=3, module="inventory"),
    make_perm("修改库存", "update_inventory", parent_code="inventory_list", sort_order=4, module="inventory"),
    make_perm("申请列表", "matrequisition_list", parent_code="inventory_manage", type="menu", sort_order=3, module="inventory"),
    make_perm("查看物料申请", "review_matrequisition", parent_code="matrequisition_list", sort_order=1, module="inventory"),
    make_perm("新建物料申请", "add_matrequisition", parent_code="matrequisition_list", sort_order=2, module="inventory"),
    make_perm("删除物料申请", "delete_matrequisition", parent_code="matrequisition_list", sort_order=3, module="inventory"),
    make_perm("修改物料申请", "update_matrequisition", parent_code="matrequisition_list", sort_order=4, module="inventory"),
    make_perm("物料采购", "material_purchase", parent_code="inventory_manage", type="menu", sort_order=4, module="inventory"),
    make_perm("查看物料采购", "review_material_purchase", parent_code="material_purchase", sort_order=1, module="inventory"),
    make_perm("新建物料采购", "add_material_purchase", parent_code="material_purchase", sort_order=2, module="inventory"),
    make_perm("删除物料采购", "delete_material_purchase", parent_code="material_purchase", sort_order=3, module="inventory"),
    make_perm("修改物料采购", "update_material_purchase", parent_code="material_purchase", sort_order=4, module="inventory"),
    make_perm("审核物料采购", "approve_material_purchase", parent_code="material_purchase", sort_order=5, module="inventory"),
    make_perm("导出物料采购", "export_material_purchase", parent_code="material_purchase", sort_order=6, module="inventory"),
    make_perm("确认价格维护", "confirm_maintained_status", parent_code="material_purchase", sort_order=7, module="inventory"),
    make_perm("确认已到货", "confirm_received_status", parent_code="material_purchase", sort_order=8, module="inventory"),
    make_perm("包装备料", "packaging_material_list", parent_code="inventory_manage", type="menu", sort_order=5, module="inventory"),
    make_perm("查看包装备料", "review_packaging_material", parent_code="packaging_material_list", sort_order=1, module="inventory"),
    make_perm("修改包装备料", "update_packaging_material", parent_code="packaging_material_list", sort_order=2, module="inventory"),
    make_perm("删除包装备料", "delete_packaging_material", parent_code="packaging_material_list", sort_order=3, module="inventory"),
    
    # ─────────────── 试模管理 ───────────────
    make_perm("试模管理", "trial_manage", parent_code="system_permission", type="menu", sort_order=4, module="trial"),
    make_perm("试模看板", "trial_dashboard", parent_code="trial_manage", type="menu", sort_order=1, module="trial"),
    make_perm("试模计划", "trial_plan", parent_code="trial_manage", type="menu", sort_order=2, module="trial"),
    make_perm("转入测试", "transfer_trial", parent_code="trial_plan", sort_order=1, module="trial"),
    make_perm("试模列表", "trial_list", parent_code="trial_manage", sort_order=3, module="trial"),
    make_perm("操作记录", "operate_record", parent_code="trial_list", sort_order=1, module="trial"),
    make_perm("操作回退", "operate_rollback", parent_code="trial_list", sort_order=2, module="trial"),
    make_perm("导出试模列表", "export_trial_list", parent_code="trial_list", sort_order=3, module="trial"),
    make_perm("试模界面", "trial_view", parent_code="trial_manage", sort_order=4, module="trial"),
    make_perm("报告管理", "trial_report", parent_code="trial_manage", type="menu", sort_order=5, module="trial"),
    make_perm("审核报告", "check_report", parent_code="trial_report", sort_order=1, module="trial"),
    make_perm("下载报告", "download_report", parent_code="trial_report", sort_order=2, module="trial"),
    make_perm("上传报告", "upload_report", parent_code="trial_report", sort_order=3, module="trial"),

    # ─────────────── 工艺管理 ───────────────
    make_perm("工艺管理", "process_manage", parent_code="system_permission", type="menu", sort_order=5, module="process"),
    make_perm("工艺列表", "process_list", parent_code="process_manage", sort_order=1, module="process"),
    # make_perm("工艺优化", "process_optimize", parent_code="process_manage", sort_order=2, module="process"),
    # make_perm("工艺规则", "process_rule", parent_code="process_manage", sort_order=3, module="process"),
    make_perm("工艺录入", "process_entry", parent_code="process_manage", sort_order=4, module="process"),
    make_perm("工艺移植", "process_transplant", parent_code="process_manage", sort_order=5, module="process"),
    # make_perm("优化列表", "optimize_list", parent_code="process_manage", sort_order=6, module="process"),

    # ─────────────── 机器管理 ───────────────
    make_perm("机器管理", "machine_manage", parent_code="system_permission", type="menu", sort_order=6, module="machine"),
    make_perm("机器列表", "machine_list", parent_code="machine_manage", type="menu", sort_order=1, module="machine"),
    make_perm("查看机器", "review_machine", parent_code="machine_list", sort_order=1, module="machine"),
    make_perm("增加机器", "add_machine", parent_code="machine_list", sort_order=2, module="machine"),
    make_perm("删除机器", "delete_machine", parent_code="machine_list", sort_order=3, module="machine"),
    make_perm("修改机器", "update_machine", parent_code="machine_list", sort_order=4, module="machine"),
    make_perm("辅助装置", "auxiliary_list", parent_code="machine_manage", type="menu", sort_order=2, module="machine"),
    make_perm("查看辅助装置", "review_auxiliary", parent_code="auxiliary_list", sort_order=1, module="machine"),
    make_perm("增加辅助装置", "add_auxiliary", parent_code="auxiliary_list", sort_order=2, module="machine"),
    make_perm("删除辅助装置", "delete_auxiliary", parent_code="auxiliary_list", sort_order=3, module="machine"),
    make_perm("修改辅助装置", "update_auxiliary", parent_code="auxiliary_list", sort_order=4, module="machine"),

    # ─────────────── 材料管理 ───────────────
    make_perm("材料管理", "polymer_manage", parent_code="system_permission", type="menu", sort_order=7, module="polymer"),
    make_perm("材料列表", "polymer_list", parent_code="polymer_manage", type="menu", sort_order=1, module="polymer"),
    make_perm("查看材料", "review_polymer", parent_code="polymer_list", sort_order=1, module="polymer"),
    make_perm("增加材料", "add_polymer", parent_code="polymer_list", sort_order=2, module="polymer"),
    make_perm("删除材料", "delete_polymer", parent_code="polymer_list", sort_order=3, module="polymer"),
    make_perm("修改材料", "update_polymer", parent_code="polymer_list", sort_order=4, module="polymer"),

    # ─────────────── 成本管理 ───────────────
    make_perm("成本管理", "cost_manage", parent_code="system_permission", type="menu", sort_order=8, module="cost"),
    make_perm("试模工时", "time_standard_list", parent_code="cost_manage", type="menu", sort_order=1, module="cost"),
    make_perm("查看试模工时", "review_standard_list", parent_code="time_standard_list", sort_order=1, module="cost"),
    make_perm("创建试模工时", "add_standard_list", parent_code="time_standard_list", sort_order=2, module="cost"),
    make_perm("删除试模工时", "delete_standard_list", parent_code="time_standard_list", sort_order=3, module="cost"),
    make_perm("修改试模工时", "update_standard_list", parent_code="time_standard_list", sort_order=4, module="cost"),
    make_perm("试模成本", "trail_costing_list", parent_code="cost_manage", type="menu", sort_order=2, module="cost"),
    make_perm("查看试模成本", "review_standard_list", parent_code="trail_costing_list", sort_order=1, module="cost"),
    make_perm("退料统计", "return_material_in_costing_list", parent_code="trail_costing_list", sort_order=2, module="cost"),

    # ─────────────── 辅助工具 ───────────────
    # make_perm("辅助工具", "assist_tools", parent_code="system_permission", type="menu", sort_order=9, module="tool"),
    # make_perm("机器性能测试", "machine_performance_trial", parent_code="assist_tools", sort_order=1, module="tool"),
    # make_perm("相对粘度测试", "relative_viscosity_trial", parent_code="assist_tools", sort_order=2, module="tool"),
    # make_perm("试验优化设计", "experimental_optimal_technology", parent_code="assist_tools", sort_order=3, module="tool"),
    # make_perm("比重计算器", "proportion_calculator", parent_code="assist_tools", sort_order=4, module="tool"),

    # ─────────────── 权限管理（用户/角色/部门）───────────────
    make_perm("权限管理", "permission_manage", parent_code="system_permission", type="menu", sort_order=10, module="admin"),

    # 部门管理
    make_perm("部门管理", "department_manage", parent_code="permission_manage", type="menu", sort_order=1, module="admin"),
    make_perm("查看部门", "review_department", parent_code="department_manage", sort_order=1, module="admin"),
    make_perm("增加部门", "add_department", parent_code="department_manage", sort_order=2, module="admin"),
    make_perm("删除部门", "delete_department", parent_code="department_manage", sort_order=3, module="admin"),
    make_perm("修改部门", "update_department", parent_code="department_manage", sort_order=4, module="admin"),

    # 角色管理
    make_perm("角色管理", "role_manage", parent_code="permission_manage", type="menu", sort_order=2, module="admin"),
    make_perm("查看角色", "review_role", parent_code="role_manage", sort_order=1, module="admin"),
    make_perm("增加角色", "add_role", parent_code="role_manage", sort_order=2, module="admin"),
    make_perm("删除角色", "delete_role", parent_code="role_manage", sort_order=3, module="admin"),
    make_perm("修改角色", "update_role", parent_code="role_manage", sort_order=4, module="admin"),

    # 用户管理
    make_perm("用户管理", "user_manage", parent_code="permission_manage", type="menu", sort_order=3, module="admin"),
    make_perm("查看用户", "review_user", parent_code="user_manage", sort_order=1, module="admin"),
    make_perm("增加用户", "add_user", parent_code="user_manage", sort_order=2, module="admin"),
    make_perm("删除用户", "delete_user", parent_code="user_manage", sort_order=3, module="admin"),
    make_perm("修改用户", "update_user", parent_code="user_manage", sort_order=4, module="admin"),

    # ─────────────── 缺陷管理 ───────────────
    # make_perm("缺陷管理", "defect_manage", parent_code="system_permission", type="menu", sort_order=11, module="defect"),
    # make_perm("缺陷列表", "defect_list", parent_code="defect_manage", sort_order=1, module="defect"),
    # make_perm("新增缺陷", "add_defect", parent_code="defect_manage", sort_order=2, module="defect"),
]
