# Generated by Django 5.2.5 on 2026-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injectionmoldingmachine',
            old_name='asset_code',
            new_name='asset_no',
        ),
        migrations.RenameField(
            model_name='injectionmoldingmachine',
            old_name='device_code',
            new_name='device_no',
        ),
        migrations.RenameField(
            model_name='mold',
            old_name='mold_code',
            new_name='mold_no',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dry_run_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_tf_trial',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sample_weight',
        ),
        migrations.AddField(
            model_name='gatingsystem',
            name='runner_length',
            field=models.FloatField(null=True, verbose_name='主流道长度 [mm]'),
        ),
        migrations.AddField(
            model_name='gatingsystem',
            name='runner_weight',
            field=models.FloatField(null=True, verbose_name='主流道重量 [g]'),
        ),
        migrations.AddField(
            model_name='gatingsystem',
            name='total_product_weight',
            field=models.FloatField(null=True, verbose_name='产品总重量 [g]'),
        ),
        migrations.AddField(
            model_name='mold',
            name='mov_half_locating_ring_height',
            field=models.FloatField(null=True, verbose_name='动模定位圈高度 [mm]'),
        ),
        migrations.AddField(
            model_name='mold',
            name='mov_half_locating_ring_inner_dia',
            field=models.FloatField(null=True, verbose_name='动模定位圈内径 [mm]'),
        ),
        migrations.AddField(
            model_name='mold',
            name='mov_half_locating_ring_outer_dia',
            field=models.FloatField(null=True, verbose_name='动模定位圈外径 [mm]'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='cavity_layout',
            field=models.CharField(help_text='如：1x1,2x2，1+1， A+B+C等', max_length=50, null=True, verbose_name='模腔布局'),
        ),
        migrations.AlterField(
            model_name='project',
            name='next_trial_stage',
            field=models.IntegerField(default=0, null=True, verbose_name='下一试模阶段'),
        ),
    ]
