"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import pymysql

pymysql.version_info = (1, 4, 13, "final", 0)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "@g0u1x5=h!6s$(_4k_u!_tvdl=%rwah69ihgw-=734@wk^^q^*"

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = os.getenv('DJANGO_ENVIRONMENT', 'development')
if ENVIRONMENT == 'production':
    DEBUG = False
else:
    DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = ["channels", "gis.admin", "django_extensions", "hsmolding", "mdprocess", "mqtt.apps.mqttConfig"]

MIDDLEWARE = [
    "gis.common.django_ext.middleware.ApiMiddleware",
    "gis.common.django_ext.middleware.OperationLogMiddleware",
]

ROOT_URLCONF = "base.urls"
ASGI_APPLICATION = "base.routing.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ]
        },
    }
]

WSGI_APPLICATION = "base.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": "127.0.0.1",
        # "NAME": "midea_test_0824",
        "NAME": "yizumi_molding",
        "USER": "root",
        "PASSWORD": "123456",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "zh-cn"

TIME_ZONE = "Asia/Chongqing"

SESSION_COOKIE_AGE = 60 * 60

USE_I18N = False

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"

MONGO_DB_HSMOLDING = "molding"  # 模鼎
MONGO_HOST = "127.0.0.1"
MONGO_PORT = 27017
MONGO_ADDR = "127.0.0.1:27017"
MONGO_USER = ""
MONGO_PASSWORD = ""

REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379

# 模板所在位置
TEMPLATE_PATH = "hsmolding/templates/"

# 文件存储位置
FILE_STORAGE_PATH = "/opt/storage/"

# 模具导入文件
MOLD_PATH = "/opt/mold/"

# 二维码所在位置
QRCODE_PATH = "/opt/media/3/qrcode/"

# 导出文件所在位置 (已弃用)
REPORT_SAVING_PATH = "/opt/report/"

# MES="http://kunpeng.yizumi.com:82"
MES="https://iiot2.yizumi.com"

# log位置
LOG_FILE = "/tmp/hsmolding.log"

# 检测 tmp 文件夹
if not os.path.exists("/tmp"):
    os.mkdir("/tmp")

# CELERY STUFF
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# mqtt 服务
MQTT_ENABLED = True
MQTT_HOST = "127.0.0.1"
MQTT_PORT = 1883


try:
    from .env_settings import *  # noqa: F403 F401
except ImportError:
    print("no env specified settings loaded, use default.")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(asctime)s %(message)s"},
        "detail": {
            "format": "%(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - " "Line: %(lineno)d -  %(message)s"
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "detail"},
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": LOG_FILE,
            "formatter": "detail",
        },
    },
    "root": {"level": "INFO", "handlers": ["console", "file"]},
}
