from marshmallow import fields
from gis.common.django_ext.forms import BaseSchema


class ExpertDefectInfoItemSchema(BaseSchema):
    label = fields.String(required=False, allow_none=True)  # 缺陷的中文名称
    desc = fields.String(required=False, allow_none=True)  # 缺陷的大写字母
    level = fields.String(required=False, allow_none=True)
    position = fields.String(required=False, allow_none=True)
    feedback = fields.String(required=False, allow_none=True)
    count = fields.Integer(required=False, allow_none=True)
    remark = fields.String(required=False, allow_none=True)


class ExpertProcessSchema(BaseSchema):
    request = fields.String(required=False, allow_none=True)
    company_id = fields.Integer(required=False, allow_none=True)
    status = fields.String(required=False, allow_none=True)

    mold_id = fields.Integer(required=False, allow_none=True)

    process_index_id = fields.Integer(required=False, allow_none=True)
    process_no = fields.String(required=False, allow_none=True)

    machine_id = fields.Integer(required=False, allow_none=True)
    machine_serial_no = fields.String(required=False, allow_none=True)

    product_weight = fields.Float(required=False, allow_none=True)
    opt_nums = fields.Integer(required=False, allow_none=True)

    polymer_id = fields.Integer(required=False, allow_none=True)
    polymer_abbreviation = fields.String(required=False, allow_none=True)

    inject_part = fields.String(required=False, allow_none=True)

    VP_switch_mode = fields.Integer(required=False, allow_none=True)  # VP切换模式
    decompressure_mode_before_metering = fields.Integer(required=False, allow_none=True)  # 储前松退模式
    decompressure_mode_after_metering = fields.Integer(required=False, allow_none=True)  # 储后松退模式

    # 注射
    injection_stage = fields.Integer(required=False, allow_none=True)

    IP0 = fields.Float(required=False, allow_none=True)
    IV0 = fields.Float(required=False, allow_none=True)
    IL0 = fields.Float(required=False, allow_none=True)
    IP1 = fields.Float(required=False, allow_none=True)
    IV1 = fields.Float(required=False, allow_none=True)
    IL1 = fields.Float(required=False, allow_none=True)
    IP2 = fields.Float(required=False, allow_none=True)
    IV2 = fields.Float(required=False, allow_none=True)
    IL2 = fields.Float(required=False, allow_none=True)
    IP3 = fields.Float(required=False, allow_none=True)
    IV3 = fields.Float(required=False, allow_none=True)
    IL3 = fields.Float(required=False, allow_none=True)
    IP4 = fields.Float(required=False, allow_none=True)
    IV4 = fields.Float(required=False, allow_none=True)
    IL4 = fields.Float(required=False, allow_none=True)
    IP5 = fields.Float(required=False, allow_none=True)
    IV5 = fields.Float(required=False, allow_none=True)
    IL5 = fields.Float(required=False, allow_none=True)

    IT = fields.Float(required=False, allow_none=True)
    ID = fields.Float(required=False, allow_none=True)
    CT = fields.Float(required=False, allow_none=True)

    # 保压
    holding_stage = fields.Integer(required=False, allow_none=True)

    INIT_PP = fields.Float(required=False, allow_none=True)
    INIT_PV = fields.Float(required=False, allow_none=True)
    INIT_PT = fields.Float(required=False, allow_none=True)

    PP0 = fields.Float(required=False, allow_none=True)
    PV0 = fields.Float(required=False, allow_none=True)
    PT0 = fields.Float(required=False, allow_none=True)
    PP1 = fields.Float(required=False, allow_none=True)
    PV1 = fields.Float(required=False, allow_none=True)
    PT1 = fields.Float(required=False, allow_none=True)
    PP2 = fields.Float(required=False, allow_none=True)
    PV2 = fields.Float(required=False, allow_none=True)
    PT2 = fields.Float(required=False, allow_none=True)
    PP3 = fields.Float(required=False, allow_none=True)
    PV3 = fields.Float(required=False, allow_none=True)
    PT3 = fields.Float(required=False, allow_none=True)
    PP4 = fields.Float(required=False, allow_none=True)
    PV4 = fields.Float(required=False, allow_none=True)
    PT4 = fields.Float(required=False, allow_none=True)

    # VP切换
    VPTM = fields.Integer(required=False, allow_none=True)
    VPTT = fields.Float(required=False, allow_none=True)
    VPTL = fields.Float(required=False, allow_none=True)
    VPTP = fields.Float(required=False, allow_none=True)
    VPTV = fields.Float(required=False, allow_none=True)

    # 计量
    metering_stage = fields.Integer(required=False, allow_none=True)

    MP0 = fields.Float(required=False, allow_none=True)
    MSR0 = fields.Float(required=False, allow_none=True)
    MBP0 = fields.Float(required=False, allow_none=True)
    ML0 = fields.Float(required=False, allow_none=True) 
    MP1 = fields.Float(required=False, allow_none=True)
    MSR1 = fields.Float(required=False, allow_none=True)
    MBP1 = fields.Float(required=False, allow_none=True)
    ML1 = fields.Float(required=False, allow_none=True)
    MP2 = fields.Float(required=False, allow_none=True)
    MSR2 = fields.Float(required=False, allow_none=True)
    MBP2 = fields.Float(required=False, allow_none=True)
    ML2 = fields.Float(required=False, allow_none=True)
    MP3 = fields.Float(required=False, allow_none=True)
    MSR3 = fields.Float(required=False, allow_none=True)
    MBP3 = fields.Float(required=False, allow_none=True)
    ML3 = fields.Float(required=False, allow_none=True)

    DMBM = fields.Integer(required=False, allow_none=True)
    DMAM = fields.Integer(required=False, allow_none=True)

    DPBM = fields.Float(required=False, allow_none=True)
    DVBM = fields.Float(required=False, allow_none=True)
    DDBM = fields.Float(required=False, allow_none=True)
    DTBM = fields.Float(required=False, allow_none=True)

    DPAM = fields.Float(required=False, allow_none=True)
    DVAM = fields.Float(required=False, allow_none=True)
    DDAM = fields.Float(required=False, allow_none=True)
    DTAM = fields.Float(required=False, allow_none=True)

    MD = fields.Float(required=False, allow_none=True)
    MEL = fields.Float(required=False, allow_none=True)

    # 料筒温度
    barrel_temperature_stage = fields.Integer(required=False, allow_none=True)

    NT = fields.Float(required=False, allow_none=True)
    BT1 = fields.Float(required=False, allow_none=True)
    BT2 = fields.Float(required=False, allow_none=True)
    BT3 = fields.Float(required=False, allow_none=True)
    BT4 = fields.Float(required=False, allow_none=True)
    BT5 = fields.Float(required=False, allow_none=True)
    BT6 = fields.Float(required=False, allow_none=True)
    BT7 = fields.Float(required=False, allow_none=True)
    BT8 = fields.Float(required=False, allow_none=True)
    BT9 = fields.Float(required=False, allow_none=True)

    # 热流道时序控制时间
    SCVN = fields.Integer(required=False, allow_none=True)
    SCT0 = fields.Float(required=False, allow_none=True)
    SCT1 = fields.Float(required=False, allow_none=True)
    SCT2 = fields.Float(required=False, allow_none=True)
    SCT3 = fields.Float(required=False, allow_none=True)
    SCT4 = fields.Float(required=False, allow_none=True)
    SCT5 = fields.Float(required=False, allow_none=True)
    SCT6 = fields.Float(required=False, allow_none=True)
    SCT7 = fields.Float(required=False, allow_none=True)
    SCT8 = fields.Float(required=False, allow_none=True)
    SCT9 = fields.Float(required=False, allow_none=True)

    # 模温设定值
    MT = fields.Float(required=False, allow_none=True)
    MTN = fields.Integer(required=False, allow_none=True)
    MT0 = fields.Float(required=False, allow_none=True)
    MT1 = fields.Float(required=False, allow_none=True)
    MT2 = fields.Float(required=False, allow_none=True)
    MT3 = fields.Float(required=False, allow_none=True)
    MT4 = fields.Float(required=False, allow_none=True)
    MT5 = fields.Float(required=False, allow_none=True)
    MT6 = fields.Float(required=False, allow_none=True)
    MT7 = fields.Float(required=False, allow_none=True)
    MT8 = fields.Float(required=False, allow_none=True)
    MT9 = fields.Float(required=False, allow_none=True)
    MT10 = fields.Float(required=False, allow_none=True)
    MT11 = fields.Float(required=False, allow_none=True)
    MT12 = fields.Float(required=False, allow_none=True)
    MT13 = fields.Float(required=False, allow_none=True)
    MT14 = fields.Float(required=False, allow_none=True)
    MT15 = fields.Float(required=False, allow_none=True)
    MT16 = fields.Float(required=False, allow_none=True)
    MT17 = fields.Float(required=False, allow_none=True)
    MT18 = fields.Float(required=False, allow_none=True)
    MT19 = fields.Float(required=False, allow_none=True)

    # 热流道温度
    HRN = fields.Integer(required=False, allow_none=True)  # 热流道段数
    HRT0 = fields.Float(required=False, allow_none=True)
    HRT1 = fields.Float(required=False, allow_none=True)
    HRT2 = fields.Float(required=False, allow_none=True)
    HRT3 = fields.Float(required=False, allow_none=True)
    HRT4 = fields.Float(required=False, allow_none=True)
    HRT5 = fields.Float(required=False, allow_none=True)
    HRT6 = fields.Float(required=False, allow_none=True)
    HRT7 = fields.Float(required=False, allow_none=True)
    HRT8 = fields.Float(required=False, allow_none=True)
    HRT9 = fields.Float(required=False, allow_none=True)
    HRT10 = fields.Float(required=False, allow_none=True)
    HRT11 = fields.Float(required=False, allow_none=True)
    HRT12 = fields.Float(required=False, allow_none=True)
    HRT13 = fields.Float(required=False, allow_none=True)
    HRT14 = fields.Float(required=False, allow_none=True)
    HRT15 = fields.Float(required=False, allow_none=True)
    HRT16 = fields.Float(required=False, allow_none=True)
    HRT17 = fields.Float(required=False, allow_none=True)
    HRT18 = fields.Float(required=False, allow_none=True)
    HRT19 = fields.Float(required=False, allow_none=True)
    HRT20 = fields.Float(required=False, allow_none=True)
    HRT21 = fields.Float(required=False, allow_none=True)
    HRT22 = fields.Float(required=False, allow_none=True)
    HRT23 = fields.Float(required=False, allow_none=True)
    HRT24 = fields.Float(required=False, allow_none=True)
    HRT25 = fields.Float(required=False, allow_none=True)
    HRT26 = fields.Float(required=False, allow_none=True)
    HRT27 = fields.Float(required=False, allow_none=True)
    HRT28 = fields.Float(required=False, allow_none=True)
    HRT29 = fields.Float(required=False, allow_none=True)
    HRT30 = fields.Float(required=False, allow_none=True)
    HRT31 = fields.Float(required=False, allow_none=True)
    HRT32 = fields.Float(required=False, allow_none=True)
    HRT33 = fields.Float(required=False, allow_none=True)
    HRT34 = fields.Float(required=False, allow_none=True)
    HRT35 = fields.Float(required=False, allow_none=True)
    HRT36 = fields.Float(required=False, allow_none=True)
    HRT37 = fields.Float(required=False, allow_none=True)
    HRT38 = fields.Float(required=False, allow_none=True)
    HRT39 = fields.Float(required=False, allow_none=True)
    HRT40 = fields.Float(required=False, allow_none=True)
    HRT41 = fields.Float(required=False, allow_none=True)
    HRT42 = fields.Float(required=False, allow_none=True)
    HRT43 = fields.Float(required=False, allow_none=True)
    HRT44 = fields.Float(required=False, allow_none=True)
    HRT45 = fields.Float(required=False, allow_none=True)
    HRT46 = fields.Float(required=False, allow_none=True)
    HRT47 = fields.Float(required=False, allow_none=True)
    HRT48 = fields.Float(required=False, allow_none=True)
    HRT49 = fields.Float(required=False, allow_none=True)

    actual_product_weight = fields.Float(required=False, allow_none=True)
    defect_info = fields.Nested(ExpertDefectInfoItemSchema, many=True)

    B000 = fields.String(required=False, allow_none=True)
    B001 = fields.String(required=False, allow_none=True)
    B002 = fields.String(required=False, allow_none=True)
    B003 = fields.String(required=False, allow_none=True)
    B004 = fields.String(required=False, allow_none=True)
    B005 = fields.String(required=False, allow_none=True)
    B006 = fields.String(required=False, allow_none=True)
    B007 = fields.String(required=False, allow_none=True)
    B008 = fields.String(required=False, allow_none=True)
    B009 = fields.String(required=False, allow_none=True)
    B010 = fields.String(required=False, allow_none=True)
    B011 = fields.String(required=False, allow_none=True)
    B012 = fields.String(required=False, allow_none=True)
    B013 = fields.String(required=False, allow_none=True)
    B014 = fields.String(required=False, allow_none=True)
    B015 = fields.String(required=False, allow_none=True)
    B016 = fields.String(required=False, allow_none=True)
    B017 = fields.String(required=False, allow_none=True)
    B018 = fields.String(required=False, allow_none=True)
    B019 = fields.String(required=False, allow_none=True)
    B020 = fields.String(required=False, allow_none=True)
    B021 = fields.String(required=False, allow_none=True)
    B022 = fields.String(required=False, allow_none=True)
    B023 = fields.String(required=False, allow_none=True)
    B024 = fields.String(required=False, allow_none=True)
    B025 = fields.String(required=False, allow_none=True)
    B026 = fields.String(required=False, allow_none=True)
    B027 = fields.String(required=False, allow_none=True)
    B028 = fields.String(required=False, allow_none=True)
    B029 = fields.String(required=False, allow_none=True)
    B030 = fields.String(required=False, allow_none=True)
    B031 = fields.String(required=False, allow_none=True)
    B032 = fields.String(required=False, allow_none=True)
    B033 = fields.String(required=False, allow_none=True)
    B034 = fields.String(required=False, allow_none=True)
    B035 = fields.String(required=False, allow_none=True)
    B036 = fields.String(required=False, allow_none=True)
    B037 = fields.String(required=False, allow_none=True)
    B038 = fields.String(required=False, allow_none=True)
    B039 = fields.String(required=False, allow_none=True)
    B040 = fields.String(required=False, allow_none=True)
    B041 = fields.String(required=False, allow_none=True)
    B042 = fields.String(required=False, allow_none=True)
    B043 = fields.String(required=False, allow_none=True)
    B044 = fields.String(required=False, allow_none=True)
    B045 = fields.String(required=False, allow_none=True)
    B046 = fields.String(required=False, allow_none=True)
    B047 = fields.String(required=False, allow_none=True)
    B048 = fields.String(required=False, allow_none=True)
    B049 = fields.String(required=False, allow_none=True)
    B050 = fields.String(required=False, allow_none=True)
    